export const INDONESIA_PROVINCES = [
    "Aceh",
    "Sumatera Utara",
    "Sumatera Barat",
    "Riau",
    "Kepulauan Riau",
    "Jambi",
    "Sumatera Selatan",
    "Kepulauan Bangka Belitung",
    "Bengkulu",
    "Lampung",
    "DKI Jakarta",
    "Jawa Barat",
    "Banten",
    "Jawa Tengah",
    "DI Yogyakarta",
    "Jawa Timur",
    "Bali",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Kalimantan Barat",
    "Kalimantan Tengah",
    "Kalimantan Selatan",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Sulawesi Utara",
    "Sulawesi Tengah",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Gorontalo",
    "Sulawesi Barat",
    "Maluku",
    "Maluku Utara",
    "Papua",
    "Papua Barat",
    "Papua Selatan",
    "Papua Tengah",
    "Papua Pegunungan",
    "Papua Barat Daya"
];

export const DUMMY_CITIES = [
    "Jakarta Pusat",
    "Jakarta Timur",
    "Jakarta Barat",
    "Jakarta Selatan",
    "Jakarta Utara",
    "Bandung",
    "Surabaya",
    "Semarang",
    "Medan",
    "Palembang",
    "Makassar",
    "Denpasar",
    "Yogyakarta",
    "Malang",
    "Bogor",
    "Tangerang",
    "Bekasi",
    "Depok",
    "Solo",
    "Banjarmasin"
];
